[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\b/home/vs)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc9\0\0\0\r\0\0\ar\0\0\x4\xe\0\0\x3\xc9\0\0\0\r\0\0\ar\0\0\x4\xe\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc9\0\0\0\r\0\0\ar\0\0\x4\xe)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(938 952)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/vs/Downloads/Explaining%20the%20barber%20pole%20effect%20from%20origins%20of%20light%20_%20Optics%20puzzles%202.mp4, file:///home/vs/Downloads/DALL%C2%B7E%202023-12-23%2017.17.59%20-%20photons%20to%20photo.png, file:///home/vs/Downloads/WhatsApp%20Video%202024-04-08%20at%2022.25.46%281%29.mp4
times=0, 0, 0
