preload = ~/.config/wallpaper/sim_blackhole.png
# preload = ~/.config/wallpaper/mountain.png
# preload = ~/.config/wallpaper/1or0.jpg
preload = ~/.config/wallpaper/leaf.jpg
# preload = ~/.config/wallpaper/speedhole.jpg
# preload = ~/.config/wallpaper/windows10.jpg
# preload = ~/.config/wallpaper/WormHole_3.jpg
# preload = ~/.config/wallpaper/sagittarius_a.jpg
# preload = ~/.config/wallpaper/kiteaboveplane.jpg
# preload = ~/.config/wallpaper/optimistic_nilesum.png

#if more than one preload is desired then continue to preload other backgrounds
#preload = /path/to/next_image.png
# .. more preloads

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = HDMI-A-1,~/.config/wallpaper/sim_blackhole.png
wallpaper = eDP-1,~/.config/wallpaper/leaf.jpg
#if more than one monitor in use, can load a 2nd image
#wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
splash = false
